version: '3'

services:
  web:
    image: sdgg1126/sre-web:0.0.1
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=mysql
      - MYSQL_PW=${MYSQL_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - my_network
    ports:
      - "3000:3000"

  mysql:
    image: sdgg1126/sre-db:0.0.1
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=chris_database
      - MYSQL_USER=chris
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "chris", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:latest
    networks:
      - my_network
      

  nginx:
    image: nginx:1.18.0
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

networks:
  my_network:

